export * from './click-menu-official-callback-data.interface';
export * from './view-menu-official-callback-data.interface';
export * from './location-select-menu-official-callback-data.interface';
export * from './pic-photo-or-album-menu-official-callback-data.interface';
export * from './pic-sysphoto-menu-official-callback-data.interface';
export * from './pic-weixin-menu-official-callback-data.interface';
export * from './scancode-push-menu-official-callback-data.interface';
export * from './scancode-waitmsg-menu-official-callback-data.interface';
export * from './view-miniprogram-menu-official-callback-data.interface';
